name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:

defaults:
  run:
    shell: bash

jobs:
  tamarin:
    name: tamarin
    uses: ./.github/workflows/tamarin.yml
  proverif:
    name: proverif
    uses: ./.github/workflows/proverif.yml
  dolev-yao-star:
    name: dolev-yao-star
    uses: ./.github/workflows/dolev-yao-star.yml
